### ISSUE TITLE
Cannot run forget-me-facebook

### ISSUE THREAD

**Issue by z5Q46L6bSY1W** [johnsaigle/forget-me-facebook#13]
I'm missing an argument. Sorry, new user here.

z5Q46L6bSY1W:forget-me-facebook-master z5Q46L6bSY1W$ 
z5Q46L6bSY1W:forget-me-facebook-master z5Q46L6bSY1W$ cd forget
z5Q46L6bSY1W:forget z5Q46L6bSY1W$ scrapy crawl login
2018-04-03 14:20:53 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: forget)
2018-04-03 14:20:53 [scrapy.utils.log] INFO: Versions: lxml 4.2.1.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.4.0, w3lib 1.19.0, Twisted 17.9.0, Python 2.7.10 (default, Oct  6 2017, 22:29:07) - [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0h  27 Mar 2018), cryptography 2.2.2, Platform Darwin-17.5.0-x86_64-i386-64bit
2018-04-03 14:20:53 [scrapy.crawler] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'forget.spiders', 'SPIDER_MODULES': ['forget.spiders'], 'BOT_NAME': 'forget'}
2018-04-03 14:20:53 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
Unhandled error in Deferred:
2018-04-03 14:20:53 [twisted] CRITICAL: Unhandled error in Deferred:

2018-04-03 14:20:53 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/twisted/internet/defer.py", line 1386, in _inlineCallbacks
    result = g.send(result)
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 98, in crawl
    six.reraise(*exc_info)
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 79, in crawl
    self.spider = self._create_spider(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/scrapy/crawler.py", line 102, in _create_spider
    return self.spidercls.from_crawler(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/scrapy/spiders/__init__.py", line 51, in from_crawler
    spider = cls(*args, **kwargs)
  File "/Users/z5Q46L6bSY1W/Downloads/forget-me-facebook-master/forget/forget/spiders/facebook_spider.py", line 36, in __init__
    super().__init__(*args, **kwargs)
TypeError: super() takes at least 1 argument (0 given)

**Comment by johnsaigle** [comment]
> Python 2.7.10

We are only supporting python3. Could you verify whether this issue appears when you run it with Python3?

**Comment by z5Q46L6bSY1W** [comment]
@johnsaigle How do I run it with Python 3? Thanks.

**Comment by johnsaigle** [comment]
@z5Q46L6bSY1W Do you have Python3 installed on your system? Check if there is any output for `which python3`.

If not you'll need to install it and also make sure the required libraries (e.g. scrapy) are also installed for python3.

**Comment by z5Q46L6bSY1W** [comment]
@johnsaigle yes, I have Python3 installed: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.

I installed scrapy using pip3 and was able to run the script, but now I have a new issue. I'll file a new issue.
