### ISSUE TITLE
[login] ERROR: Failed to reach On This Day page.

### ISSUE THREAD

**Issue by z5Q46L6bSY1W** [johnsaigle/forget-me-facebook#14]
See log below. Facebook sent me an automatically generated email about this login from an unknown device (this script)...maybe that is the cause of this issue?

```
2018-05-10 14:37:40 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET https://www.facebook.com/> from <POST https://www.facebook.com/login.php?login_attempt=1&lwv=100>
2018-05-10 14:37:42 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.facebook.com/> (referer: https://www.facebook.com/login.php)
2018-05-10 14:37:42 [login] INFO: Login success.
2018-05-10 14:37:43 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.facebook.com/onthisday> (referer: https://www.facebook.com/)
2018-05-10 14:37:43 [login] ERROR: Failed to reach On This Day page.
2018-05-10 14:37:43 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.facebook.com/onthisday> (referer: https://www.facebook.com/)
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/Users/z5Q46L6bSY1W/Downloads/forget-me-facebook-master/forget/forget/spiders/facebook_spider.py", line 78, in on_this_day
    write_response_body_to_file('onthisday_fail.html', response.body)
NameError: name 'write_response_body_to_file' is not defined
2018-05-10 14:37:43 [scrapy.core.engine] INFO: Closing spider (finished)
2018-05-10 14:37:43 [scrapy.core.engine] INFO: Spider closed (finished)
```

**Comment by johnsaigle** [comment]
Hey @z5Q46L6bSY1W. That's an odd error. It looks like the login succeeded but it couldn't navigate to On this Day.

I am not surprised you got that email but judging by the error logs I don't think it would have interfered.

### Anyway....

After doing more research it looks like deleting from On this Day is more complicated than simply navigating to the timeline, so I've deleted the part of the code that tries to access that page. As such, this issue is "solved" in that we don't need to get to On this Day anymore 😅 

Apologies for the delay and ✨ **Thanks for the interest!** ✨  I got inspired to resume development on this since you were engaging with the repo. Please keep following along as I build this up in my spare time!
